### ISSUE TITLE
Clean up & rename this repo (or merge it into repo-tools)

### ISSUE THREAD

**Issue by kdmccormick** [openedx/terraform-github#57]
### Background

We're not going to use Terraform to manage the GitHub organization. Rather, it looks like we're going to have a collection of scripts here (like `repo_checks.py`) to help us automatically check & fix certain aspects of the org, and then manually manage the org  otherwise.

### Tasks

- [ ] confirm with the team that the background, as stated, is indeed the direction we want to go
- [ ] Either:
  - [ ] (a) Decide to keep this as its own repo. If so, then:
    - [ ] Clean up the things we don't use
    - [ ] Set it up with a requirements file, managed by pip-tools
    - [ ] Set it up with any tooling we think would be useful: pycodestyle/black/isort, linting, mypy
    - [ ] Rename it. Ideas: `axim-tools`, `github-tools`, `axim-github-tools`, `github-management` etc.
  - [ ] (b) Merge this into repo-tools

### Notes

**Arguments in favor of keeping this separate:**
* We (Axim) are the only people who should run these scripts. That's different than repo tools, which serves several audiences.
* If we choose to change directions (e.g. go back to Terraform) we can still do it all in this repo.
* We can officially maintain this repo without taking on all of repo-tools.
* We can grant CC rights to repo-tools without granting merge rights to potentially security-related scripts in this repo.

**Arguments in favor of merging into repo-tools:**
* Repo tools already has pip-tools set up and (I think) already has regular upgrades going
* One place for all repo-related tooling
* Fewer repos ==> fewer things to audit & manage

**Comment by kdmccormick** [comment]
@feanil FYI - for when we get around it

**Comment by kdmccormick** [comment]
First I'm going to fix repo_checks' tests & linting: https://github.com/openedx/terraform-github/pull/63

Then I'm going to move repo_checks to repo-tools: https://github.com/openedx/repo-tools/pull/382

Then I'll archive this repo.

@feanil let me know if you have any objections to that plan.

**Comment by feanil** [comment]
That all sounds correct to me.
